### PR TITLE
Added Frozen Time Mode.

### PR DESCRIPTION
**Pull request by mhashim6**
This mode will not change images based on time.

### CODE REVIEW

**Comment by mhashim6** [comment]
Btw, I didn't give much thought about the image that I put there, if you find a better fit, feel free to change it, however, I also made the textcolor of the textview white, so it would stand out from the other "contextual views".

**Comment by Zer0xFF** [comment]
Thanks for the PR. On quick review it looks good, but I'll have a good look once I merge my on going branches.

Ya the text colour is better white as that's the colour of the time/text in the statusbar. I might change the other ones to white.
But it might work better to hide the other views when single image mode is enabled.

**Comment by Zer0xFF** [comment]
@mhashim6 the image looks fine to me, but I don't think it was added as part of the commit?

P.S HZD, one hell of a game.

**Comment by mhashim6** [comment]
For some reason, it didn't get tracked, I'll fix when I'm home.
I haven't played it yet, but it looks really promising.

**Comment by mhashim6** [comment]
@Thunder07 I added the missing drawable in the last commit.

**Comment by Zer0xFF** [comment]
I was notified when the new commit was added, I just didn't get the chance to mess around with this yet. Thanks

**Comment by Zer0xFF** [comment]
Thanks @mhashim6, I've merged the code into master and added a small change.
I'm hiding the daily views when frozen is enabled and vice versa.

**Comment by mhashim6** [comment]
Nice!

**Pull request merged**
